;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 2.0.8
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(in-package :libevent2-ssl)



(cl:defconstant #.(le::lispify "_EVENT_HAVE_OPENSSL" 'constant) 1)

(cffi:defcenum #.(le::lispify "bufferevent_ssl_state" 'enumname)
	(#.(le::lispify "BUFFEREVENT_SSL_OPEN" 'enumvalue :keyword) #.0)
	(#.(le::lispify "BUFFEREVENT_SSL_CONNECTING" 'enumvalue :keyword) #.1)
	(#.(le::lispify "BUFFEREVENT_SSL_ACCEPTING" 'enumvalue :keyword) #.2))

(cffi:defcfun ("bufferevent_openssl_filter_new" #.(le::lispify "bufferevent_openssl_filter_new" 'function)) :pointer
  (base :pointer)
  (underlying :pointer)
  (ssl :pointer)
  (state #.(le::lispify "bufferevent_ssl_state" 'enumname))
  (options :int))

(cffi:defcfun ("bufferevent_openssl_socket_new" #.(le::lispify "bufferevent_openssl_socket_new" 'function)) :pointer
  (base :pointer)
  (fd :int)
  (ssl :pointer)
  (state #.(le::lispify "bufferevent_ssl_state" 'enumname))
  (options :int))

(cffi:defcfun ("bufferevent_openssl_get_ssl" #.(le::lispify "bufferevent_openssl_get_ssl" 'function)) :pointer
  (bufev :pointer))

(cffi:defcfun ("bufferevent_ssl_renegotiate" #.(le::lispify "bufferevent_ssl_renegotiate" 'function)) :int
  (bev :pointer))

(cffi:defcfun ("bufferevent_get_openssl_error" #.(le::lispify "bufferevent_get_openssl_error" 'function)) :unsigned-long
  (bev :pointer))


